'use client'
import './globals.css'
// import {Inter} from 'next/font/google'
import 'react-photo-view/dist/react-photo-view.css';
import css from '../lib/layout.module.css'
import HeadNav from "/lib/HeadNav";
// const inter = Inter({subsets: ['latin']})
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',


// }
export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <HeadNav/>
        <div className={css.mt}>
            {children}</div>
        </body>
        </html>
    )
}
